/// Countries shown on phone login (aligned with web `phone-login.blade.php`).
class LoginCountry {
  const LoginCountry({
    required this.code,
    required this.flag,
    required this.dialCode,
    required this.name,
    required this.supported,
  });

  final String code;
  final String flag;
  final String dialCode;
  final String name;
  final bool supported;
}

/// Ghana first, then alphabetical by name.
List<LoginCountry> get loginCountriesSorted {
  final list = List<LoginCountry>.from(kLoginCountries);
  list.sort((a, b) {
    if (a.code == 'GH') return -1;
    if (b.code == 'GH') return 1;
    return a.name.compareTo(b.name);
  });
  return list;
}

const LoginCountry kDefaultLoginCountry = LoginCountry(
  code: 'GH',
  flag: '🇬🇭',
  dialCode: '+233',
  name: 'Ghana',
  supported: true,
);

const List<LoginCountry> kLoginCountries = [
  // Africa
  LoginCountry(
    code: 'GH',
    flag: '🇬🇭',
    dialCode: '+233',
    name: 'Ghana',
    supported: true,
  ),
  LoginCountry(
    code: 'NG',
    flag: '🇳🇬',
    dialCode: '+234',
    name: 'Nigeria',
    supported: false,
  ),
  LoginCountry(
    code: 'KE',
    flag: '🇰🇪',
    dialCode: '+254',
    name: 'Kenya',
    supported: false,
  ),
  LoginCountry(
    code: 'ZA',
    flag: '🇿🇦',
    dialCode: '+27',
    name: 'South Africa',
    supported: false,
  ),
  LoginCountry(
    code: 'EG',
    flag: '🇪🇬',
    dialCode: '+20',
    name: 'Egypt',
    supported: false,
  ),
  LoginCountry(
    code: 'ET',
    flag: '🇪🇹',
    dialCode: '+251',
    name: 'Ethiopia',
    supported: false,
  ),
  LoginCountry(
    code: 'TZ',
    flag: '🇹🇿',
    dialCode: '+255',
    name: 'Tanzania',
    supported: false,
  ),
  LoginCountry(
    code: 'UG',
    flag: '🇺🇬',
    dialCode: '+256',
    name: 'Uganda',
    supported: false,
  ),
  LoginCountry(
    code: 'ZW',
    flag: '🇿🇼',
    dialCode: '+263',
    name: 'Zimbabwe',
    supported: false,
  ),
  LoginCountry(
    code: 'ZM',
    flag: '🇿🇲',
    dialCode: '+260',
    name: 'Zambia',
    supported: false,
  ),
  LoginCountry(
    code: 'AO',
    flag: '🇦🇴',
    dialCode: '+244',
    name: 'Angola',
    supported: false,
  ),
  LoginCountry(
    code: 'MA',
    flag: '🇲🇦',
    dialCode: '+212',
    name: 'Morocco',
    supported: false,
  ),
  LoginCountry(
    code: 'DZ',
    flag: '🇩🇿',
    dialCode: '+213',
    name: 'Algeria',
    supported: false,
  ),
  LoginCountry(
    code: 'TN',
    flag: '🇹🇳',
    dialCode: '+216',
    name: 'Tunisia',
    supported: false,
  ),
  LoginCountry(
    code: 'CM',
    flag: '🇨🇲',
    dialCode: '+237',
    name: 'Cameroon',
    supported: false,
  ),
  LoginCountry(
    code: 'CI',
    flag: '🇨🇮',
    dialCode: '+225',
    name: "Côte d'Ivoire",
    supported: false,
  ),
  LoginCountry(
    code: 'SN',
    flag: '🇸🇳',
    dialCode: '+221',
    name: 'Senegal',
    supported: false,
  ),
  LoginCountry(
    code: 'RW',
    flag: '🇷🇼',
    dialCode: '+250',
    name: 'Rwanda',
    supported: false,
  ),
  LoginCountry(
    code: 'BW',
    flag: '🇧🇼',
    dialCode: '+267',
    name: 'Botswana',
    supported: false,
  ),
  LoginCountry(
    code: 'MW',
    flag: '🇲🇼',
    dialCode: '+265',
    name: 'Malawi',
    supported: false,
  ),
  // Americas
  LoginCountry(
    code: 'US',
    flag: '🇺🇸',
    dialCode: '+1',
    name: 'United States',
    supported: false,
  ),
  LoginCountry(
    code: 'CA',
    flag: '🇨🇦',
    dialCode: '+1',
    name: 'Canada',
    supported: false,
  ),
  LoginCountry(
    code: 'MX',
    flag: '🇲🇽',
    dialCode: '+52',
    name: 'Mexico',
    supported: false,
  ),
  LoginCountry(
    code: 'BR',
    flag: '🇧🇷',
    dialCode: '+55',
    name: 'Brazil',
    supported: false,
  ),
  LoginCountry(
    code: 'AR',
    flag: '🇦🇷',
    dialCode: '+54',
    name: 'Argentina',
    supported: false,
  ),
  LoginCountry(
    code: 'CO',
    flag: '🇨🇴',
    dialCode: '+57',
    name: 'Colombia',
    supported: false,
  ),
  LoginCountry(
    code: 'PE',
    flag: '🇵🇪',
    dialCode: '+51',
    name: 'Peru',
    supported: false,
  ),
  LoginCountry(
    code: 'VE',
    flag: '🇻🇪',
    dialCode: '+58',
    name: 'Venezuela',
    supported: false,
  ),
  LoginCountry(
    code: 'CL',
    flag: '🇨🇱',
    dialCode: '+56',
    name: 'Chile',
    supported: false,
  ),
  LoginCountry(
    code: 'EC',
    flag: '🇪🇨',
    dialCode: '+593',
    name: 'Ecuador',
    supported: false,
  ),
  LoginCountry(
    code: 'GT',
    flag: '🇬🇹',
    dialCode: '+502',
    name: 'Guatemala',
    supported: false,
  ),
  LoginCountry(
    code: 'CU',
    flag: '🇨🇺',
    dialCode: '+53',
    name: 'Cuba',
    supported: false,
  ),
  LoginCountry(
    code: 'BO',
    flag: '🇧🇴',
    dialCode: '+591',
    name: 'Bolivia',
    supported: false,
  ),
  LoginCountry(
    code: 'DO',
    flag: '🇩🇴',
    dialCode: '+1',
    name: 'Dominican Republic',
    supported: false,
  ),
  LoginCountry(
    code: 'HN',
    flag: '🇭🇳',
    dialCode: '+504',
    name: 'Honduras',
    supported: false,
  ),
  LoginCountry(
    code: 'PY',
    flag: '🇵🇾',
    dialCode: '+595',
    name: 'Paraguay',
    supported: false,
  ),
  LoginCountry(
    code: 'SV',
    flag: '🇸🇻',
    dialCode: '+503',
    name: 'El Salvador',
    supported: false,
  ),
  LoginCountry(
    code: 'NI',
    flag: '🇳🇮',
    dialCode: '+505',
    name: 'Nicaragua',
    supported: false,
  ),
  LoginCountry(
    code: 'CR',
    flag: '🇨🇷',
    dialCode: '+506',
    name: 'Costa Rica',
    supported: false,
  ),
  LoginCountry(
    code: 'PA',
    flag: '🇵🇦',
    dialCode: '+507',
    name: 'Panama',
    supported: false,
  ),
  // Asia
  LoginCountry(
    code: 'IN',
    flag: '🇮🇳',
    dialCode: '+91',
    name: 'India',
    supported: false,
  ),
  LoginCountry(
    code: 'CN',
    flag: '🇨🇳',
    dialCode: '+86',
    name: 'China',
    supported: false,
  ),
  LoginCountry(
    code: 'JP',
    flag: '🇯🇵',
    dialCode: '+81',
    name: 'Japan',
    supported: false,
  ),
  LoginCountry(
    code: 'KR',
    flag: '🇰🇷',
    dialCode: '+82',
    name: 'South Korea',
    supported: false,
  ),
  LoginCountry(
    code: 'ID',
    flag: '🇮🇩',
    dialCode: '+62',
    name: 'Indonesia',
    supported: false,
  ),
  LoginCountry(
    code: 'PK',
    flag: '🇵🇰',
    dialCode: '+92',
    name: 'Pakistan',
    supported: false,
  ),
  LoginCountry(
    code: 'BD',
    flag: '🇧🇩',
    dialCode: '+880',
    name: 'Bangladesh',
    supported: false,
  ),
  LoginCountry(
    code: 'PH',
    flag: '🇵🇭',
    dialCode: '+63',
    name: 'Philippines',
    supported: false,
  ),
  LoginCountry(
    code: 'VN',
    flag: '🇻🇳',
    dialCode: '+84',
    name: 'Vietnam',
    supported: false,
  ),
  LoginCountry(
    code: 'TH',
    flag: '🇹🇭',
    dialCode: '+66',
    name: 'Thailand',
    supported: false,
  ),
  LoginCountry(
    code: 'MY',
    flag: '🇲🇾',
    dialCode: '+60',
    name: 'Malaysia',
    supported: false,
  ),
  LoginCountry(
    code: 'SG',
    flag: '🇸🇬',
    dialCode: '+65',
    name: 'Singapore',
    supported: false,
  ),
  LoginCountry(
    code: 'MM',
    flag: '🇲🇲',
    dialCode: '+95',
    name: 'Myanmar',
    supported: false,
  ),
  LoginCountry(
    code: 'KH',
    flag: '🇰🇭',
    dialCode: '+855',
    name: 'Cambodia',
    supported: false,
  ),
  LoginCountry(
    code: 'LA',
    flag: '🇱🇦',
    dialCode: '+856',
    name: 'Laos',
    supported: false,
  ),
  LoginCountry(
    code: 'TW',
    flag: '🇹🇼',
    dialCode: '+886',
    name: 'Taiwan',
    supported: false,
  ),
  LoginCountry(
    code: 'HK',
    flag: '🇭🇰',
    dialCode: '+852',
    name: 'Hong Kong',
    supported: false,
  ),
  LoginCountry(
    code: 'MO',
    flag: '🇲🇴',
    dialCode: '+853',
    name: 'Macau',
    supported: false,
  ),
  LoginCountry(
    code: 'MN',
    flag: '🇲🇳',
    dialCode: '+976',
    name: 'Mongolia',
    supported: false,
  ),
  LoginCountry(
    code: 'NP',
    flag: '🇳🇵',
    dialCode: '+977',
    name: 'Nepal',
    supported: false,
  ),
  LoginCountry(
    code: 'LK',
    flag: '🇱🇰',
    dialCode: '+94',
    name: 'Sri Lanka',
    supported: false,
  ),
  LoginCountry(
    code: 'AF',
    flag: '🇦🇫',
    dialCode: '+93',
    name: 'Afghanistan',
    supported: false,
  ),
  LoginCountry(
    code: 'IQ',
    flag: '🇮🇶',
    dialCode: '+964',
    name: 'Iraq',
    supported: false,
  ),
  LoginCountry(
    code: 'SA',
    flag: '🇸🇦',
    dialCode: '+966',
    name: 'Saudi Arabia',
    supported: false,
  ),
  LoginCountry(
    code: 'AE',
    flag: '🇦🇪',
    dialCode: '+971',
    name: 'United Arab Emirates',
    supported: false,
  ),
  LoginCountry(
    code: 'IL',
    flag: '🇮🇱',
    dialCode: '+972',
    name: 'Israel',
    supported: false,
  ),
  LoginCountry(
    code: 'TR',
    flag: '🇹🇷',
    dialCode: '+90',
    name: 'Turkey',
    supported: false,
  ),
  LoginCountry(
    code: 'IR',
    flag: '🇮🇷',
    dialCode: '+98',
    name: 'Iran',
    supported: false,
  ),
  LoginCountry(
    code: 'JO',
    flag: '🇯🇴',
    dialCode: '+962',
    name: 'Jordan',
    supported: false,
  ),
  LoginCountry(
    code: 'LB',
    flag: '🇱🇧',
    dialCode: '+961',
    name: 'Lebanon',
    supported: false,
  ),
  LoginCountry(
    code: 'KW',
    flag: '🇰🇼',
    dialCode: '+965',
    name: 'Kuwait',
    supported: false,
  ),
  LoginCountry(
    code: 'OM',
    flag: '🇴🇲',
    dialCode: '+968',
    name: 'Oman',
    supported: false,
  ),
  LoginCountry(
    code: 'QA',
    flag: '🇶🇦',
    dialCode: '+974',
    name: 'Qatar',
    supported: false,
  ),
  LoginCountry(
    code: 'BH',
    flag: '🇧🇭',
    dialCode: '+973',
    name: 'Bahrain',
    supported: false,
  ),
  LoginCountry(
    code: 'YE',
    flag: '🇾🇪',
    dialCode: '+967',
    name: 'Yemen',
    supported: false,
  ),
  LoginCountry(
    code: 'SY',
    flag: '🇸🇾',
    dialCode: '+963',
    name: 'Syria',
    supported: false,
  ),
  LoginCountry(
    code: 'PS',
    flag: '🇵🇸',
    dialCode: '+970',
    name: 'Palestine',
    supported: false,
  ),
  // Europe
  LoginCountry(
    code: 'GB',
    flag: '🇬🇧',
    dialCode: '+44',
    name: 'United Kingdom',
    supported: false,
  ),
  LoginCountry(
    code: 'FR',
    flag: '🇫🇷',
    dialCode: '+33',
    name: 'France',
    supported: false,
  ),
  LoginCountry(
    code: 'DE',
    flag: '🇩🇪',
    dialCode: '+49',
    name: 'Germany',
    supported: false,
  ),
  LoginCountry(
    code: 'IT',
    flag: '🇮🇹',
    dialCode: '+39',
    name: 'Italy',
    supported: false,
  ),
  LoginCountry(
    code: 'ES',
    flag: '🇪🇸',
    dialCode: '+34',
    name: 'Spain',
    supported: false,
  ),
  LoginCountry(
    code: 'NL',
    flag: '🇳🇱',
    dialCode: '+31',
    name: 'Netherlands',
    supported: false,
  ),
  LoginCountry(
    code: 'BE',
    flag: '🇧🇪',
    dialCode: '+32',
    name: 'Belgium',
    supported: false,
  ),
  LoginCountry(
    code: 'CH',
    flag: '🇨🇭',
    dialCode: '+41',
    name: 'Switzerland',
    supported: false,
  ),
  LoginCountry(
    code: 'AT',
    flag: '🇦🇹',
    dialCode: '+43',
    name: 'Austria',
    supported: false,
  ),
  LoginCountry(
    code: 'SE',
    flag: '🇸🇪',
    dialCode: '+46',
    name: 'Sweden',
    supported: false,
  ),
  LoginCountry(
    code: 'NO',
    flag: '🇳🇴',
    dialCode: '+47',
    name: 'Norway',
    supported: false,
  ),
  LoginCountry(
    code: 'DK',
    flag: '🇩🇰',
    dialCode: '+45',
    name: 'Denmark',
    supported: false,
  ),
  LoginCountry(
    code: 'FI',
    flag: '🇫🇮',
    dialCode: '+358',
    name: 'Finland',
    supported: false,
  ),
  LoginCountry(
    code: 'PL',
    flag: '🇵🇱',
    dialCode: '+48',
    name: 'Poland',
    supported: false,
  ),
  LoginCountry(
    code: 'PT',
    flag: '🇵🇹',
    dialCode: '+351',
    name: 'Portugal',
    supported: false,
  ),
  LoginCountry(
    code: 'GR',
    flag: '🇬🇷',
    dialCode: '+30',
    name: 'Greece',
    supported: false,
  ),
  LoginCountry(
    code: 'IE',
    flag: '🇮🇪',
    dialCode: '+353',
    name: 'Ireland',
    supported: false,
  ),
  LoginCountry(
    code: 'CZ',
    flag: '🇨🇿',
    dialCode: '+420',
    name: 'Czech Republic',
    supported: false,
  ),
  LoginCountry(
    code: 'HU',
    flag: '🇭🇺',
    dialCode: '+36',
    name: 'Hungary',
    supported: false,
  ),
  LoginCountry(
    code: 'RO',
    flag: '🇷🇴',
    dialCode: '+40',
    name: 'Romania',
    supported: false,
  ),
  LoginCountry(
    code: 'BG',
    flag: '🇧🇬',
    dialCode: '+359',
    name: 'Bulgaria',
    supported: false,
  ),
  LoginCountry(
    code: 'HR',
    flag: '🇭🇷',
    dialCode: '+385',
    name: 'Croatia',
    supported: false,
  ),
  LoginCountry(
    code: 'RS',
    flag: '🇷🇸',
    dialCode: '+381',
    name: 'Serbia',
    supported: false,
  ),
  LoginCountry(
    code: 'SK',
    flag: '🇸🇰',
    dialCode: '+421',
    name: 'Slovakia',
    supported: false,
  ),
  LoginCountry(
    code: 'SI',
    flag: '🇸🇮',
    dialCode: '+386',
    name: 'Slovenia',
    supported: false,
  ),
  LoginCountry(
    code: 'EE',
    flag: '🇪🇪',
    dialCode: '+372',
    name: 'Estonia',
    supported: false,
  ),
  LoginCountry(
    code: 'LV',
    flag: '🇱🇻',
    dialCode: '+371',
    name: 'Latvia',
    supported: false,
  ),
  LoginCountry(
    code: 'LT',
    flag: '🇱🇹',
    dialCode: '+370',
    name: 'Lithuania',
    supported: false,
  ),
  LoginCountry(
    code: 'UA',
    flag: '🇺🇦',
    dialCode: '+380',
    name: 'Ukraine',
    supported: false,
  ),
  LoginCountry(
    code: 'RU',
    flag: '🇷🇺',
    dialCode: '+7',
    name: 'Russia',
    supported: false,
  ),
  LoginCountry(
    code: 'BY',
    flag: '🇧🇾',
    dialCode: '+375',
    name: 'Belarus',
    supported: false,
  ),
  LoginCountry(
    code: 'MD',
    flag: '🇲🇩',
    dialCode: '+373',
    name: 'Moldova',
    supported: false,
  ),
  LoginCountry(
    code: 'IS',
    flag: '🇮🇸',
    dialCode: '+354',
    name: 'Iceland',
    supported: false,
  ),
  LoginCountry(
    code: 'LU',
    flag: '🇱🇺',
    dialCode: '+352',
    name: 'Luxembourg',
    supported: false,
  ),
  LoginCountry(
    code: 'MT',
    flag: '🇲🇹',
    dialCode: '+356',
    name: 'Malta',
    supported: false,
  ),
  LoginCountry(
    code: 'CY',
    flag: '🇨🇾',
    dialCode: '+357',
    name: 'Cyprus',
    supported: false,
  ),
  LoginCountry(
    code: 'AL',
    flag: '🇦🇱',
    dialCode: '+355',
    name: 'Albania',
    supported: false,
  ),
  LoginCountry(
    code: 'MK',
    flag: '🇲🇰',
    dialCode: '+389',
    name: 'North Macedonia',
    supported: false,
  ),
  LoginCountry(
    code: 'BA',
    flag: '🇧🇦',
    dialCode: '+387',
    name: 'Bosnia and Herzegovina',
    supported: false,
  ),
  // Oceania
  LoginCountry(
    code: 'AU',
    flag: '🇦🇺',
    dialCode: '+61',
    name: 'Australia',
    supported: false,
  ),
  LoginCountry(
    code: 'NZ',
    flag: '🇳🇿',
    dialCode: '+64',
    name: 'New Zealand',
    supported: false,
  ),
  LoginCountry(
    code: 'FJ',
    flag: '🇫🇯',
    dialCode: '+679',
    name: 'Fiji',
    supported: false,
  ),
  LoginCountry(
    code: 'PG',
    flag: '🇵🇬',
    dialCode: '+675',
    name: 'Papua New Guinea',
    supported: false,
  ),
  LoginCountry(
    code: 'NC',
    flag: '🇳🇨',
    dialCode: '+687',
    name: 'New Caledonia',
    supported: false,
  ),
  LoginCountry(
    code: 'PF',
    flag: '🇵🇫',
    dialCode: '+689',
    name: 'French Polynesia',
    supported: false,
  ),
];
